# Generated by Django 4.1 on 2022-08-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
